app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
Route::get('/test', 'HomeController@test');

Route::resource('roles', 'RoleController');
Route::resource('permissions', 'PermissionController');

Route::resource('cooperants', 'CooperantController');
Route::get('bookings/map', 'BookingController@getMap');
Route::get('bookings/getMapJSON', 'BookingController@getMapJSON');
Route::resource('bookings', 'BookingController');

Route::resource('processing', 'ProcessingController');

Route::resource('config', 'ConfigController');

Route::resource('users', 'UserController');

Route::get('/luka', 'CooperantController@test');

Route::get('/landing', function(){
   return view('layouts.landingmaster');
});

resources/views/partials/main-content.blade.php
<div class="col-md-10 htbg">
  <h1 class="page-header">Dashboard</h1>
  <h2 class="sub-header">Section title</h2>
</div>

resources/views/partials/navigation.blade.php
<!-- NAV -->
<nav class="navbar navbar-custom no--br">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img src="{{ asset('img/logo.png') }}" alt="olivio" style="width: 60px; margin-top: -10px;"/></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <!-- Authentication Links -->
        @if (Auth::guest())
          <li><a href="{{ url('/login') }}">Login</a></li>
          <li><a href="{{ url('/register') }}">Register</a></li>
        @else
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                {{ Auth::user()->name }} <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
            </ul>
          </li>
        @endif
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

resources/views/partials/sidebar.blade.php
<div class="col-md-3">
  <div class="panel element-style">
    
    <a href="#menu3" class="lgi border-none" data-toggle="collapse" data-parent="#MainMenu">
      <i class="fa fa-calendar-plus-o"></i>&nbsp; Predbilježbe <i class="fa fa-caret-down pull-right"></i>
    </a>
    <div class="collapse" id="menu3">
      <a href="{{ route('bookings.create') }}" class="lgi">Dodaj predbilježbu</a>
      <a href="{{ route('bookings.index') }}" class="lgi">Pregledaj predbilježbe</a>
    </div>

    @if(Auth::user()->hasPermission('upravljanje-obradom-maslina'))
      <a href="#menu5" class="lgi border-none" data-toggle="collapse" data-parent="#MainMenu">
        <i class="fa fa-lemon-o "></i>&nbsp; Obrada masline <i class="fa fa-caret-down pull-right"></i>
      </a>
      <div class="collapse" id="menu5">
        <a href="{{ route('processing.index') }}" class="lgi">Pregledaj obrade</a>
        <a href="{{ route('processing.create') }}" class="lgi">Dodaj obradu</a>
      </div>
    @endif

    @if(Auth::user()->hasRole('administrator'))
      <a href="#menu2" class="lgi border-none" data-toggle="collapse" data-parent="#MainMenu">
        <i class="fa fa-key"></i>&nbsp; Upravljanje pristupom <i class="fa fa-caret-down pull-right"></i>
      </a>
      <div class="collapse" id="menu2">
        <a href="{{ route('users.index') }}" class="lgi">Korisnici</a>
        <a href="{{ route('roles.index') }}" class="lgi">Uloge</a>
        <a href="{{ route('permissions.index') }}" class="lgi">Dopuštenja</a>
      </div>
      <a href="{{ route('users.index') }}" class="lgi border-none"  data-parent="#MainMenu">
        <i class="fa fa-key"></i>&nbsp; Korisnici
      </a>
    @endif


  </div>
</div>