app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
Route::get('/test', 'HomeController@test');

Route::resource('roles', 'RoleController');
Route::resource('permissions', 'PermissionController');

Route::resource('cooperants', 'CooperantController');
Route::get('bookings/map', 'BookingController@getMap');
Route::get('bookings/getMapJSON', 'BookingController@getMapJSON');
Route::resource('bookings', 'BookingController');

Route::resource('processing', 'ProcessingController');

Route::resource('config', 'ConfigController');

Route::resource('users', 'UserController');

Route::get('/luka', 'CooperantController@test');

Route::get('/landing', function(){
   return view('layouts.landingmaster');
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role() {
        return $this->belongsTo('App\Role');
    }

    public function hasPermission($key)
    {
        if($this->role->hasPermission($key)){
            return true;
        }

        return false;
    }

    public function hasRole($key)
    {
        if($this->role->slug == $key){
            return true;
        }

        return false;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\User;
use Illuminate\Http\Request;

use App\Http\Requests;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.index', [
            'users' => User::paginate(20)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create', [
            'roles' => Role::all()->pluck('title', 'id')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $data['password'] = bcrypt($data['password']);

        User::create($data);

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('users.edit', [
            'user' => User::findOrFail($id),
            'roles' => Role::all()->pluck('title', 'id')
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        User::find($id)->fill($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
    }
}

resources/views/users/create.blade.php
@extends("layouts.master")

@section("title", "Korisnici")

@section("main-content")
    <div class="pc no--br">
        <div class="panel-body">
            <h1>Novi korisnik</h1>
            <form action="{{ route('users.store') }}" method="POST">
                <div class="form-group">
                    <label for="name">Ime</label>
                    <input type="text" class="fc" name="name" id="name" placeholder="Ime korisnika">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="fc" name="email" id="email" placeholder="Email korisnika">
                </div>
                <div class="form-group">
                    <label for="password">Lozinka</label>
                    <input type="password" class="fc" name="password" id="password" placeholder="Lozinka korisnika">
                </div>

                <div class="form-group">
                    <label for="role_id">Uloga</label>
                    {!! Form::select('role_id', $roles, null, ['class' => 'fc']) !!}
                </div>

                <button type="submit" class="btn-cst">Dodaj korisnika</button>
                {!! csrf_field() !!}
            </form>
        </div>
    </div>
@endsection

resources/views/users/edit.blade.php
@extends("layouts.master")

@section("title", "Korisnici")

@section("main-content")
    <div class="pc no--br">
        <div class="panel-body">
            <h1>Novi korisnik</h1>
            <form action="{{ route('users.update', $user->id) }}" method="POST">
                {!! method_field('PATCH') !!}
                <div class="form-group">
                    <label for="name">Ime</label>
                    <input value="{{ $user->name }}" type="text" class="fc" name="name" id="name" placeholder="Ime korisnika">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input value="{{ $user->email }}" type="email" class="fc" name="email" id="email" placeholder="Email korisnika">
                </div>
                <div class="form-group">
                    <label for="password">Lozinka</label>
                    <input type="text" class="fc" name="password" id="password" placeholder="Lozinka korisnika">
                </div>

                <div class="form-group">
                    <label for="role_id">Uloga</label>
                    {!! Form::select('role_id', $roles, $user->role->id, ['class' => 'fc']) !!}
                </div>

                <button type="submit" class="btn-cst">Dodaj korisnika</button>
                {!! csrf_field() !!}
            </form>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends("layouts.master")

@section("title", "Pregledaj uloge")

@section("main-content")
    <table class="table-custom">
        <thead>
            <tr>
                <th>Ime Korisnika</th>
                <th>Email</th>
                <th>Uloga</th>
                <th>Mogućnosti</th>
            </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>{{ $user->name}}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->role->title }}</td>
                <td><a href="{{ route('users.edit', $user->id) }}">
                        <i class="fa fa-gear"></i>&nbsp;
                    </a>
                    <a class="delete-resource" data-resId="{{ $user->id }}" href="{{ route('users.destroy', $user->id) }}"><i class="fa fa-times"></i></a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection