app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
Route::get('/test', 'HomeController@test');

Route::resource('roles', 'RoleController');
Route::resource('permissions', 'PermissionController');

Route::resource('cooperants', 'CooperantController');
Route::get('bookings/map', 'BookingController@getMap');
Route::get('bookings/getMapJSON', 'BookingController@getMapJSON');
Route::resource('bookings', 'BookingController');

Route::resource('processing', 'ProcessingController');

Route::resource('config', 'ConfigController');

Route::resource('users', 'UserController');

Route::get('/luka', 'CooperantController@test');

Route::get('/landing', function(){
   return view('layouts.landingmaster');
});

app/Processing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Processing extends Model
{
    protected $fillable = ['oil_amount', 'olive_amount', 'olive_quality_id', 'booking_id',
        'oil_quality_id', 'processing_start', 'processing_end'];

    public function oliveQuality() {
    	return $this->belongsTo('App\OliveQuality');
    }

    public function oilQuality() {
    	return $this->belongsTo('App\OilQuality');
    }

    public function booking(){
        return $this->belongsTo('App\Booking');
    }
}

app/Http/Controllers/ProcessingController.php
<?php

namespace App\Http\Controllers;

use App\Booking;
use App\OilQuality;
use App\OliveQuality;
use App\Processing;
use Illuminate\Http\Request;

use App\Http\Requests;

class ProcessingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('processings.index', [
            'processings' => Processing::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $bookings = Booking::latest()->get();

        foreach($bookings as $booking){
            $bookingKey = ($booking->processing_start->toDateTimeString() . ', '. $booking->cooperant->getFullname());
            $bookingsData[$booking->id] = $bookingKey;
        }

        return view('processings.create', [
            'bookings' => $bookingsData,
            'olive_qualities' => OilQuality::all()->pluck('quality', 'id'),
            'oil_qualities' => OliveQuality::all()->pluck('quality', 'id')

        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $booking = Processing::create($request->all());

        return redirect()->route('processing.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bookings = Booking::latest()->get();

        foreach($bookings as $booking){
            $bookingKey = ($booking->processing_start->toDateTimeString() . ', '. $booking->cooperant->getFullname());
            $bookingsData[$booking->id] = $bookingKey;
        }

        return view('processings.edit', [
            'bookings' => $bookingsData,
            'olive_qualities' => OilQuality::all()->pluck('quality', 'id'),
            'oil_qualities' => OliveQuality::all()->pluck('quality', 'id'),
            'processing' => Processing::findOrFail($id)

        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Processing::find($id)->fill($request->all())->save();

        return redirect()->route('processing.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Processing::destroy($id);
    }
}

resources/views/processings/create.blade.php
@extends("layouts.master")

@section("title", "Dodaj obradu")

@section('head-styles')
    <link href="{{ asset('css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet">
@endsection

@section("main-content")
    <div class="pc no--br">
        <div class="panel-body">
            <form action="{{ route('processing.store') }}" method="POST">
                <div class="form-group">
                    <label for="booking_id">Predbilježba</label>
                    {!! Form::select('booking_id', $bookings, null, ['class' => 'fc']) !!}
                </div>
                <div class="form-group">
                    <label for="processing_start">Početak prerade</label>
                    <div class='input-group date' id='processing_start'>
                        <input type='text' class="form-control" name="processing_start"/>
            <span class="input-group-addon">
               <span class="glyphicon glyphicon-calendar"></span>
            </span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="processing_start">Kraj prerade</label>
                    <div class='input-group date' id='processing_end'>
                        <input type='text' class="form-control" name="processing_end"/>
                    <span class="input-group-addon">
                       <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="olive_amount">Količina masline (kg)</label>
                    <input type="text" class="fc" name="olive_amount" id="olive_amount" placeholder="Količina masline">
                </div>

                <div class="form-group">
                    <label for="olive_quality_id">Kvaliteta masline</label>
                    {!! Form::select('olive_quality_id', $oil_qualities, null, ['class' => 'fc']) !!}
                </div>

                <div class="form-group">
                    <label for="oil_amount">Količina maslinovog ulja (L)</label>
                    <input type="text" class="fc" name="oil_amount" id="oil_amount" placeholder="Količina maslinovog ulja">
                </div>

                <div class="form-group">
                    <label for="oil_quality_id">Kvaliteta masline</label>
                    {!! Form::select('oil_quality_id', $olive_qualities, null, ['class' => 'fc']) !!}
                </div>


                {!! csrf_field() !!}
                <button type="submit" class="btn-cst">Dodaj obradu</button>
            </form>
        </div>
    </div>
@endsection

@section('end-body-scripts')
    <script src="{{ asset('js/moment.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>

    <script>

        $('#processing_start').datetimepicker({
            format: 'Y-M-D HH:mm:ss'
        });

        $('#processing_end').datetimepicker({
            format: 'Y-M-D HH:mm:ss'
        });
    </script>
@endsection

resources/views/processings/edit.blade.php
@extends("layouts.master")

@section("title", "Dodaj obradu")

@section('head-styles')
    <link href="{{ asset('css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet">
@endsection

@section("main-content")
    <div class="pc no--br">
        <div class="panel-body">
            <form action="{{ route('processing.update', $processing->id) }}" method="POST">
                {!! method_field('PATCH') !!}
                <div class="form-group">
                    <label for="booking_id">Predbilježba</label>
                    {!! Form::select('booking_id', $bookings, $processing->booking_id, ['class' => 'fc']) !!}
                </div>
                <div class="form-group">
                    <label for="processing_start">Početak prerade</label>
                    <div class='input-group date' id='processing_start'>
                        <input value="{{ $processing->processing_start }}" type='text' class="form-control" name="processing_start"/>
            <span class="input-group-addon">
               <span class="glyphicon glyphicon-calendar"></span>
            </span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="processing_start">Kraj prerade</label>
                    <div  class='input-group date' id='processing_end'>
                        <input value="{{ $processing->processing_end }}" type='text' class="form-control" name="processing_end"/>
                    <span class="input-group-addon">
                       <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="olive_amount">Količina masline (kg)</label>
                    <input value="{{ $processing->olive_amount }}" type="text" class="fc" name="olive_amount" id="olive_amount" placeholder="Količina masline">
                </div>

                <div class="form-group">
                    <label for="olive_quality_id">Kvaliteta masline</label>
                    {!! Form::select('olive_quality_id', $oil_qualities, $processing->olive_quality_id, ['class' => 'fc']) !!}
                </div>

                <div class="form-group">
                    <label for="oil_amount">Količina maslinovog ulja (L)</label>
                    <input value="{{ $processing->oil_amount }}" type="text" class="fc" name="oil_amount" id="oil_amount" placeholder="Količina maslinovog ulja">
                </div>

                <div class="form-group">
                    <label for="oil_quality_id">Kvaliteta masline</label>
                    {!! Form::select('oil_quality_id', $olive_qualities, $processing->oil_quality_id, ['class' => 'fc']) !!}
                </div>


                {!! csrf_field() !!}
                <button type="submit" class="btn-cst">Izmjeni obradu</button>
            </form>
        </div>
    </div>
@endsection

@section('end-body-scripts')
    <script src="{{ asset('js/moment.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>

    <script>

        $('#processing_start').datetimepicker({
            format: 'Y-M-D HH:mm:ss'
        });

        $('#processing_end').datetimepicker({
            format: 'Y-M-D HH:mm:ss'
        });
    </script>
@endsection

resources/views/processings/index.blade.php
@extends("layouts.master")

@section("title", "Obrade")

@section("main-content")
		<table class="table-custom">
			<thead>
				<tr>
					<th>ID</th>
					<th>ID predbiljedžba</th>
					<th>Adresa kooperanta</th>
					<th>Količina maslina</th>
					<th>Količina ulja</th>
					<th>Kvaliteta maslina</th>
					<th>Kvaliteta ulja</th>
					<th>Mogućnosti</th>
				</tr>
			</thead>
			<tbody>
				@foreach($processings as $processing)
					<tr>
						<td>{{ $processing->id }}</td>
						<td>{{ $processing->booking_id }}</td>
						<td>{{ $processing->booking->cooperant->address->getCityCountry() }}</td>
						<td>{{ $processing->olive_amount }}</td>
						<td>{{ $processing->oil_amount }}</td>
						<td>{{ $processing->oilQuality->quality }}</td>
						<td>{{ $processing->oliveQuality->quality }}</td>
						<td><a href="{{ route('processing.edit', $processing->id) }}">
								<i class="fa fa-gear"></i>&nbsp;
							</a>
							<a class="delete-resource" data-resId="{{ $processing->id }}" href="{{ route('processing.destroy', $processing->id) }}"><i class="fa fa-times"></i></a>
						</td>
					</tr>
				@endforeach
			</tbody>
		</table>
@endsection