app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');
Route::get('/test', 'HomeController@test');

Route::resource('roles', 'RoleController');
Route::resource('permissions', 'PermissionController');

Route::resource('cooperants', 'CooperantController');
Route::get('bookings/map', 'BookingController@getMap');
Route::get('bookings/getMapJSON', 'BookingController@getMapJSON');
Route::resource('bookings', 'BookingController');

Route::resource('processing', 'ProcessingController');

Route::resource('config', 'ConfigController');

Route::resource('users', 'UserController');

Route::get('/luka', 'CooperantController@test');

Route::get('/landing', function(){
   return view('layouts.landingmaster');
});

app/Role.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\SluggableInterface;
use Cviebrock\EloquentSluggable\SluggableTrait;
use Illuminate\Database\Eloquent\Model;

class Role extends Model implements SluggableInterface
{
    use SluggableTrait;

    protected $fillable = ['title', 'slug'];
    
    public function users() {
    	return $this->belongsToMany('App\User');
    }

    public function permissions() {
    	return $this->belongsToMany('App\Permission', 'role_permission')->withTimestamps();
    }

    public function hasPermission($key){
        if(in_array($key, $this->permissions->pluck("slug")->toArray())){
            return true;
        }

        return false;
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Roles\CreateRoleRequest;
use App\Http\Requests\Roles\DeleteRoleRequest;
use App\Http\Requests\Roles\StoreRoleRequest;
use App\Permission;
use App\Repositories\PermissionsRepository;
use App\Repositories\RolesRepository;
use App\Role;
use Illuminate\Http\Request;

use App\Http\Requests;

class RoleController extends Controller
{
    private $rolesRepo;
    private $permissionsRepo;

    public function __construct(RolesRepository $rolesRepo,
                               PermissionsRepository $permissionsRepo)
    {
        $this->rolesRepo = $rolesRepo;
        $this->permissionsRepo = $permissionsRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('roles.index', [
            'roles' => $this->rolesRepo->all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('roles.create', [
            'permissions' => $this->permissionsRepo->all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRoleRequest $request)
    {
        $this->rolesRepo->store($request->all());
        return redirect()->route('roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('roles.edit',
            [
                'role' => $this->rolesRepo->findById($id),
                'permissions' => $this->permissionsRepo->all()
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CreateRoleRequest $request, $id)
    {
        $role = $this->rolesRepo->update($id, $request->all());

        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(DeleteRoleRequest $request, $id)
    {
        Role::destroy($id);
    }
}

resources/views/roles/create.blade.php
@extends("layouts.master")

@section("title", "Dodaj ulogu")

@section("main-content")
    <div class="pc no--br">
        <div class="panel-body">
            <form action="{{ route('roles.store') }}" method="POST">
                <div class="form-group">
                    <label for="title">Naziv uloge</label>
                    <input type="text" class="fc" name="title" id="title" placeholder="Naziv uloge">
                </div>
                <h4>Dopuštenja</h4>
                @foreach($permissions as $permission)
                    <div class="checkbox">
                        <label>
                            <input name="permissions[]" value="{{ $permission->id }}" type="checkbox" id="{{ $permission->slug }}"> {{ $permission->title }}
                        </label>
                    </div>
                @endforeach
                <button type="submit" class="btn-cst">Dodaj ulogu</button>
                {!! csrf_field() !!}
            </form>
        </div>
    </div>
@endsection

resources/views/roles/edit.blade.php
@extends("layouts.master")

@section("title", "Izmjeni ulogu")

@section("main-content")
    <div class="pc no--br">
        <div class="panel-body">
            <form action="{{ route('roles.update', $role->id) }}" method="POST">
                {!! method_field("PATCH") !!}
                <div class="form-group">
                    <label for="title">Naziv uloge</label>
                    <input value="{{ $role->title }}" type="text" class="fc" name="title" id="title" placeholder="Naziv uloge">
                </div>
                <h4>Dopuštenja</h4>
                @foreach($permissions as $permission)
                    <div class="checkbox">
                        <label>
                            <input
                                    @if(in_array($permission->id, $role->permissions->pluck('id')->toArray()))
                                    checked
                                    @endif
                                    name="permissions[]"
                                    value="{{ $permission->id }}"
                                    type="checkbox" id="{{ $permission->slug }}"> {{ $permission->title }}
                        </label>
                    </div>
                @endforeach
                <button type="submit" class="btn-cst">Izmjeni ulogu</button>
                {!! csrf_field() !!}
            </form>
        </div>
    </div>
@endsection

resources/views/roles/index.blade.php
@extends("layouts.master")

@section("title", "Pregledaj uloge")

@section("main-content")
    <table class="table-custom">
        <thead>
            <tr>
                <th>Ime uloge</th>
                <th>Mogućnosti</th>
            </tr>
        </thead>
        <tbody>
        @foreach($roles as $role)
            <tr>
                <td>{{ $role->title }}</td>
                <td><a href="{{ route('roles.edit', $role->id) }}">
                        <i class="fa fa-gear"></i>&nbsp;
                    </a>
                    <a class="delete-resource" data-resId="{{ $role->id }}" href="{{ route('roles.destroy', $role->id) }}"><i class="fa fa-times"></i></a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection